version: '3.1'
services:
  crud-php:
    container_name: cont-examen
    image: gonzalomarin/examen-crudphp:latest
    restart: always
    environment:
      DB_HOST: bd_mariadb
      DB_NAME: examen
      DB_USER: examen
      DB_PASSWORD: examen
    ports:
      - 8080:80
    depends_on:
      - db
  db:
    container_name: bd_mariadb
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: examen
      MARIADB_DATABASE: examen
      MARIADB_USER: examen
      MARIADB_PASSWORD: examen
    volumes:
      - mariadb_data:/var/lib/mysql
#    ports:
#      - 3306:3306
volumes:
    mariadb_data:
